### ISSUE TITLE
New feature: Change display mode when specified app is started

### ISSUE THREAD

**Issue by OtaK** [OtaK/vivid#4]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsexa

And accompanying apis.

New field in the settings, something like:
```toml
[[program_settings]]
exe_name = "r5apex.exe"
vibrance = 72
fullscreen_only = false
display_mode = "1728x1080@144Hz" # This is the new field
```
